authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication' 

urlpatterns = [
	url(r'^accounts/$', views.all_accounts, name='accounts'),
	url(r'^add-account/$', views.new_account, name='add_account'),
	url(r'^register-user/$', views.register_user, name='register_user'),
	url(r'^delete-account/(?P<account>\d+)/$', views.delete_account, name='delete-account'),
]

hardware_store/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'authentication/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'', include('inventory.urls', namespace='inventory')),
]

inventory/urls.py
from django.conf.urls import url

from . import views

app_name = 'inventory'

urlpatterns = [
	url(r'^$', views.dashboard, name='dashboard'),
	# Categories
	url(r'^item-categories/$', views.item_categories, name='item_categories'),
	url(r'^register-category/$', views.register_category, name='register_category'),
	url(r'^category/(?P<pk>\d+)/detail/$', views.category_detail, name='category_detail'),
	# Suppliers
	url(r'^new-supplier/$', views.new_supplier, name='new_supplier'),
	url(r'^register-supplier/$', views.register_supplier, name='register_supplier'),
	url(r'^suppliers/$', views.suppliers, name='suppliers'),
	# Items
	url(r'^new-item/$', views.new_item, name='new_item'),
	url(r'^register-item/$', views.register_item, name='register_item'),
	url(r'^add-stock/(?P<item>\d+)/$', views.add_stock, name='add_stock'),
	url(r'^update-stock/$', views.update_stock, name='update_stock'),
	# Sale
	url(r'^sales/$', views.sales, name='sales'),
	url(r'^get-item/(?P<item>\d+)/$', views.get_item, name='get_item'),
	url(r'^record-sale/$', views.record_sale, name='record_sale'),
	# Supply records
	url(r'^supply-records/$', views.supply_records, name='supply_records'),
	url(r'^add-supply/$', views.new_supply_record, name='add_supply_record'),
	url(r'^register-supply/$', views.record_supply, name='record_supply'),
]

authentication/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

@login_required(login_url='login')
def new_account(request):
	return render(request, 'authentication/create-account.html')

@login_required(login_url='login')
def register_user(request):
	if request.method=='POST':
		username = request.POST['username']
		email = request.POST['email']
		password = request.POST['password']

		if not(User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
			User.objects.create_user(username, email, password)
			messages.success(request, "Success! Account detail successfully recorded.")
			return redirect('authentication:accounts')
		else:
			messages.warning(request, "Error! Username with that email already exists")
			return redirect('authentication:register_user')

	else:
		return render(request, 'authentication/register-user.html')

@login_required(login_url='login')
def all_accounts(request):
	users = User.objects.all()
	context = {
		'users' : users,
	}
	return render(request, 'authentication/accounts.html', context)


@login_required(login_url='login')
def delete_account(request, account):
	farm = get_object_or_404(User, pk=account)
	farm.delete()
	messages.success(request, 'Account successfully deleted')
	return redirect('authentication:accounts')

authentication/templates/authentication/accounts.html
{% extends "base.html" %}

{% block title %}Accounts{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages %}
			<div {% ifequal message.tags 'error' %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endifequal %}>{{ message }}</div>
			{% endfor %}
			{% endif %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{% url 'authentication:add_account' %}" class="btn btn-primary pull-right">Add account</a>
					<h3>All Accounts</h3>
				</div>
				<div class="panel-body">
					<table class="table table-bordered table-responsive">
						<thead>
							<th>Username</th>
							<th>Email</th>
							<th>Joined on</th>
							<th>Last login</th>
						</thead>
						<tbody>
							{% for user in users %}
							<tr>
								<td><a href="">{{ user.username }}</a></td>
								<td>{{ user.email }}</td>
								<td>{{ user.date_joined }}</td>
								<td>{{ user.last_login }}</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="4"><h3>No users registered yet</h3></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

authentication/templates/authentication/create-account.html
{% extends "base.html" %}

{% block title %}Create Account{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>Add Account</h3>
				</div>
				<div class="panel-body">
					<div class="col-md-offset-3 col-md-6">
						<form class="form form-horizontal" method="POST" action="{% url 'authentication:register_user' %}">{% csrf_token%}
							<div class="form-group">
								<label>Username</label>
								<input type="text" name="username" class="form-control" placeholder="Enter username" required>
							</div>
							<div class="form-group">
								<label>Email</label>
								<input type="email" name="email" class="form-control" placeholder="Enter email">
							</div>
							<div class="form-group">
								<label>Password</label>
								<input type="password" name="password" class="form-control" placeholder="Enter password" required>
							</div>
							<div class="buttons">
								<button type="reset" class="btn btn-danger">Cancel</button>
								<button type="submit" class="btn btn-primary">Add account</button>
							</div>
							
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

authentication/templates/authentication/login.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>IMS - Login</title>
<!--// Stylesheets //-->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" media="screen" />
<link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" media="screen" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<script type="text/javascript" src="{% static 'assets/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/icheck.min.js' %}"></script>
</head>

<body>
<!-- Wrapper Start -->
<div class="loginwrapper">
	<span class="circle"></span>
	<div class="loginone">
    	<header>
        	<a href="dashboard1.html"><img src="{% static 'assets/images/logo.png' %}" alt="" /></a>
            <p>Enter your credentials to login to your account</p>
        </header>
        <form method="POST" action="{% url 'login' %}">{% csrf_token %}
        	<div class="username">
        		<input type="text" class="form-control" name="username" placeholder="Enter your username" />
                <i class="glyphicon glyphicon-user"></i>
            </div>
            <div class="password">
            	<input type="password" class="form-control" name="password" placeholder="Enter your password" />
                <i class="glyphicon glyphicon-lock"></i>
            </div>
            <div class="custom-radio-checkbox">
                <input tabindex="1" type="checkbox" class="bluecheckradios">
                <label>Remember me</label>
            </div>
			<script>
				$(document).ready(function(){
				  $('.bluecheckradios').iCheck({
					checkboxClass: 'icheckbox_flat-blue',
					radioClass: 'iradio_flat-blue',
					increaseArea: '20%' // optional
				  });
				});  	
			</script>
            <input type="submit" class="btn btn-primary style2" value="Sign In" />
        </form>
        <footer>
        	<a href="#" class="forgot pull-left">I forgot my password</a>
            <!-- <a href="#" class="register pull-right">Create account</a> -->
            <div class="clear"></div>
        </footer>
    </div>
</div>
<!-- Wrapper End -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js' %}','ga');

  ga('create', 'UA-42761673-1', 'extracoding.com');
  ga('send', 'pageview');

</script>

</body>
</html>

<!-- Localized -->