hardware_store/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'authentication/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'', include('inventory.urls', namespace='inventory')),
]

inventory/urls.py
from django.conf.urls import url

from . import views

app_name = 'inventory'

urlpatterns = [
	url(r'^$', views.dashboard, name='dashboard'),
	# Categories
	url(r'^item-categories/$', views.item_categories, name='item_categories'),
	url(r'^register-category/$', views.register_category, name='register_category'),
	url(r'^category/(?P<pk>\d+)/detail/$', views.category_detail, name='category_detail'),
	# Suppliers
	url(r'^new-supplier/$', views.new_supplier, name='new_supplier'),
	url(r'^register-supplier/$', views.register_supplier, name='register_supplier'),
	url(r'^suppliers/$', views.suppliers, name='suppliers'),
	# Items
	url(r'^new-item/$', views.new_item, name='new_item'),
	url(r'^register-item/$', views.register_item, name='register_item'),
	url(r'^add-stock/(?P<item>\d+)/$', views.add_stock, name='add_stock'),
	url(r'^update-stock/$', views.update_stock, name='update_stock'),
	# Sale
	url(r'^sales/$', views.sales, name='sales'),
	url(r'^get-item/(?P<item>\d+)/$', views.get_item, name='get_item'),
	url(r'^record-sale/$', views.record_sale, name='record_sale'),
	# Supply records
	url(r'^supply-records/$', views.supply_records, name='supply_records'),
	url(r'^add-supply/$', views.new_supply_record, name='add_supply_record'),
	url(r'^register-supply/$', views.record_supply, name='record_supply'),
]

inventory/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Item_categorie(models.Model):
	category_name = models.CharField(max_length=200)
	created_on = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.category_name

class Item(models.Model):
	category = models.ForeignKey(Item_categorie)
	item_name = models.CharField(max_length=200)
	brand = models.CharField(max_length=200)
	description = models.TextField(blank=True)
	quantity = models.FloatField(default=0)
	price = models.FloatField()
	created_on = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.item_name

class Supplier(models.Model):
	supplier_name = models.CharField(max_length=200)
	contact = models.CharField(max_length=200)
	added_on = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.supplier_name

class Item_sale(models.Model):
	item = models.ForeignKey(Item)
	quantity = models.FloatField()
	amount = models.FloatField()
	date_sold = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "{} - {}".format(self.item, self.quantity)

class Item_supply(models.Model):
	supplier = models.ForeignKey(Supplier)
	items_supplied = models.CharField(max_length=200)
	item_brand = models.CharField(max_length=200, blank=True)
	quantity = models.FloatField()
	amount = models.FloatField()
	date_supplied = models.DateField(default=timezone.now)
	pay_status = models.IntegerField(default=0)

	def __str__(self):
		return "supplier: {}, Items: {}, Quantity: {}".format(self.supplier, self.items_supplied, self.quantity)

inventory/views.py
from .models import Item_categorie, Item, Supplier, Item_sale, Item_supply
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Sum, Count
from django.shortcuts import render, redirect, get_object_or_404
import datetime, calendar


# Create your views here.
@login_required(login_url='login')
def dashboard(request):
	today = datetime.datetime.now()
	mwaka = today.year

	accounts = User.objects.all().count()
	items = Item.objects.all()
	suppliers = Supplier.objects.all().count()
	sales = Item_sale.objects.filter(date_sold__year=mwaka, date_sold__month=today.month).aggregate(total_sales=Sum('amount'))
	expenses = Item_supply.objects.filter(date_supplied__year=mwaka, date_supplied__month=today.month).aggregate(total_expenses=Sum('amount'))
	sales_graph = Item_sale.objects.filter(date_sold__year=mwaka, date_sold__month=today.month).values('item').annotate(total_amount=Sum('amount'))
	current_month_sales = Item_sale.objects.filter(date_sold__year=mwaka, date_sold__month=today.month).aggregate(current_month=Sum('amount'))

	context = {
		'accounts' : accounts,
		'current_month_sales' : current_month_sales,
		'expenses' : expenses,
		'items' : items,
		'sales' : sales,
		'sales_graph' : sales_graph,
		'suppliers' : suppliers,
	}

	return render(request, "inventory/dashboard.html", context)

@login_required(login_url='login')
def item_categories(request):
	categories = Item_categorie.objects.all()

	context = {
		'categories' : categories,
	}

	return render(request, 'inventory/item-categories.html', context)

@login_required(login_url='login')
def register_category(request):
	if request.method=="POST":
		category_name = request.POST['category_name']
		if Item_categorie.objects.filter(category_name=category_name).exists():
			messages.error(request, "Error! That category name already exists. Try another one.")
			return redirect('inventory:item_categories')
		else:
			category = Item_categorie(category_name=category_name).save()
			messages.success(request, "Success! Item category details have been added.")
			return redirect('inventory:item_categories')
	else:
		return redirect('inventory:item_categories')

@login_required(login_url='login')
def category_detail(request, pk):
	category = get_object_or_404(Item_categorie, pk=pk)
	context = {
		'category' : category,
	}

	return render(request, 'inventory/category-items.html', context)


# Suppliers module
@login_required(login_url='login')
def new_supplier(request):
	return render(request, "inventory/new-supplier.html")

@login_required(login_url='login')
def register_supplier(request):
	if request.method=="POST":
		supplier_name = request.POST['supplier_name']
		contact = request.POST['contact']
		if Supplier.objects.filter(supplier_name=supplier_name).exists():
			messages.error(request, "Error! That supplier name already exists. Try another one.")
			return redirect('inventory:suppliers')
		else:
			supplier = Supplier(supplier_name=supplier_name, contact=contact).save()
			messages.success(request, "Success! Supplier details have been added.")
			return redirect('inventory:suppliers')
	else:
		return redirect('inventory:suppliers')

@login_required(login_url='login')
def suppliers(request):
	suppliers = Supplier.objects.all()
	context = {
		'suppliers' : suppliers,
	}

	return render(request, 'inventory/suppliers.html', context)


# Items module
@login_required(login_url='login')
def new_item(request):
	categories = Item_categorie.objects.all()

	context = {
		'categories' : categories,
	}

	return render(request, "inventory/new-item.html", context)

@login_required(login_url='login')
def register_item(request):
	if request.method=="POST":
		category = get_object_or_404(Item_categorie, pk=request.POST['category'])
		item_name = request.POST['item_name']
		brand = request.POST['brand']
		description = request.POST['description']
		quantity = request.POST['quantity']
		price = request.POST['price']
		if Item.objects.filter(category=category, item_name=item_name).exists():
			item = get_object_or_404(Item, item_name=item_name)
			item.quantity = item.quantity + quantity
			item.save()
			messages.warning(request, "Warning! That item name already exists. It's quantity has been updated.")
			return redirect('inventory:category_detail', pk=category.pk)
		else:
			item = Item(category=category, item_name=item_name, brand=brand, description=description, quantity=quantity, price=price).save()
			messages.success(request, "Success! Item details have been added.")
			return redirect('inventory:category_detail', pk=category.pk)
	else:
		return redirect('inventory:new_item')


@login_required(login_url='login')
def get_item(request, item):
	item = get_object_or_404(Item, pk=item)
	context = {
		'item' : item,
	}

	return render(request, 'inventory/record-sale.html', context)

@login_required(login_url='login')
def add_stock(request, item):
	item = get_object_or_404(Item, pk=item)
	context = {
		'item' : item,
	}

	return render(request, 'inventory/add-stock.html', context)

@login_required(login_url='login')
def update_stock(request):
	if request.method == "POST":
		item = get_object_or_404(Item, pk=request.POST['item'])
		item.quantity = item.quantity + float(request.POST['quantity'])
		item.save()
		messages.success(request, "Success! Item stock record updated successfully!")
		return redirect('inventory:sales')
	else:
		return redirect('inventory:sales')





# Sales module
@login_required(login_url='login')
def sales(request):
	sales = Item_sale.objects.all()
	items = Item.objects.all()

	context = {
		'sales' : sales,
		'items' : items,
	}

	return render(request, 'inventory/sales-records.html', context)

@login_required(login_url='login')
def record_sale(request):
	if request.method == "POST":
		item = get_object_or_404(Item, pk=request.POST['item'])
		quantity = float(request.POST['quantity'])
		amount = float(item.price) * quantity

		if quantity > item.quantity:
			messages.error(request, "Error! The quantity exceeds the available stock!")
			return redirect('inventory:sales')
		else:
			sale = Item_sale(item = item, quantity=quantity, amount=amount).save()
			item.quantity = item.quantity - quantity
			item.save()
			messages.success(request, "Success! Sale record details added!")
			return redirect('inventory:sales')
	else:
		return redirect('inventory:sales')


# Supply records module
@login_required(login_url='login')
def new_supply_record(request):
	suppliers = Supplier.objects.all()

	context = {
		'suppliers' : suppliers,
	}

	return render(request, "inventory/add-supply.html", context)


@login_required(login_url='login')
def record_supply(request):
	if request.method == "POST":
		supplier = get_object_or_404(Supplier, pk=request.POST['supplier'])
		items_supplied = request.POST['items_supplied']
		item_brand = request.POST['item_brand']
		quantity = float(request.POST['quantity'])
		amount = float(request.POST['amount'])

		
		supply = Item_supply(supplier=supplier, items_supplied=items_supplied, item_brand=item_brand, quantity=quantity, amount=amount).save()
		messages.success(request, "Success! Supply record details added!")
		return redirect('inventory:supply_records')
	else:
		return redirect('inventory:supply_records')


@login_required(login_url='login')
def supply_records(request):
	records = Item_supply.objects.all().order_by('-date_supplied')
	suppliers = Supplier.objects.all()

	context = {
		'records' : records,
		'suppliers' : suppliers,
	}

	return render(request, 'inventory/supply-records.html', context)






			

inventory/templates/inventory/add-stock.html
{% extends "base.html" %}

{% block title %}Add Stock{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>Add stock</h3>
				</div>
				<div class="panel-body">
					<div class="col-md-offset-3 col-md-6">
						<form class="form form-horizontal" method="POST" action="{% url 'inventory:update_stock' %}">{% csrf_token%}
							<input type="hidden" name="item" value="{{ item.pk }}">
							<div class="form-group">
								<label>Item name</label>
								<input type="text" name="item_name" class="form-control" value="{{ item.item_name }}" required disabled>
							</div>
							<div class="form-group">
								<label>Quantity</label>
								<input type="text" name="quantity" class="form-control" placeholder="Enter item quantity">
							</div>
							<div class="buttons">
								<button type="reset" class="btn btn-danger">Cancel</button>
								<button type="submit" class="btn btn-primary">Update stock</button>
							</div>
							
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/add-supply.html
{% extends "base.html" %}

{% block title %}Add Supply Record{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>Add supply record</h3>
				</div>
				<div class="panel-body">
					<div class="col-md-offset-3 col-md-6">
						<form class="form form-horizontal" method="POST" action="{% url 'inventory:record_supply' %}">{% csrf_token%}
							<div class="form-group">
								<label>Supplier</label>
								<select name="supplier" class="form-control">
									<option selected disabled>--Select supplier--</option>
									{% for supplier in suppliers %}
									<option value="{{ supplier.pk }}">{{ supplier.supplier_name }}</option>
									{% endfor %}
								</select>
							</div>
							<div class="form-group">
								<label>Item name</label>
								<input type="text" name="items_supplied" class="form-control" placeholder="Enter item name" required>
							</div>
							<div class="form-group">
								<label>Item brand</label>
								<input type="text" name="item_brand" class="form-control" placeholder="Enter item brand" required>
							</div>
							<div class="form-group">
								<label>Quantity</label>
								<input type="text" name="quantity" class="form-control" placeholder="Enter item quantity">
							</div>
							<div class="form-group">
								<label>Amount Due</label>
								<input type="text" name="amount" class="form-control" placeholder="Enter total amount due">
							</div>
							<div class="buttons">
								<button type="reset" class="btn btn-danger">Cancel</button>
								<button type="submit" class="btn btn-primary">Save record</button>
							</div>
							
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/category-items.html
{% extends "base.html" %}

{% block title %}Category Items{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages %}
			<div {% ifequal message.tags 'error' %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endifequal %}>{{ message }}</div>
			{% endfor %}
			{% endif %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{% url 'inventory:new_item' %}" class="btn btn-primary pull-right">Add item</a>
					<h3>{{ category.category_name }} Items</h3>
				</div>
				<div class="panel-body">
					<table class="table table-bordered table-responsive">
						<thead>
							<th>Name</th>
							<th>Brand</th>
							<th>Stock</th>
							<th>Price</th>
							<th>Added on</th>
							<th>Action</th>
						</thead>
						<tbody>
							{% for item in category.item_set.all %}
							<tr>
								<td><a href="">{{ item.item_name }}</a></td>
								<td>{{ item.brand }}</td>
								<td>{{ item.quantity }}</td>
								<td>{{ item.price }}</td>
								<td>{{ item.created_on }}</td>
								<td>
									<a href="{% url 'inventory:get_item' item.pk %}"><span class="glyphicon glyphicon-export"></span> sell</a> | 
									<a href="{% url 'inventory:add_stock' item.pk %}"><span class="glyphicon glyphicon-download"></span> stock</a>
								</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="4"><h3>No {{ category.category_name }} items registered yet</h3></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/item-categories.html
{% extends "base.html" %}

{% block title %}Item Categories{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages %}
			<div {% ifequal message.tags 'error' %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endifequal %}>{{ message }}</div>
			{% endfor %}
			{% endif %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a data-toggle="modal" href="#myModal" class="btn btn-primary pull-right">Add Category</a>
					<h3>All Accounts</h3>
				</div>
				<div class="panel-body">
					<table class="table table-bordered table-responsive">
						<thead>
							<th>Category</th>
							<th>Created on</th>
						</thead>
						<tbody>
							{% for category in categories %}
							<tr>
								<td><a href="{% url 'inventory:category_detail' category.pk %}">{{ category.category_name }}</a></td>
								<td>{{ category.created_on }}</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="4"><h3>No categories registered yet</h3></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/new-item.html
{% extends "base.html" %}

{% block title %}Add Item{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>Add Item</h3>
				</div>
				<div class="panel-body">
					<div class="col-md-offset-3 col-md-6">
						<form class="form form-horizontal" method="POST" action="{% url 'inventory:register_item' %}">{% csrf_token%}
							<div class="form-group">
								<label>Category</label>
								<select name="category" class="form-control">
									<option selected disabled>--Select category--</option>
									{% for category in categories %}
									<option value="{{ category.pk }}">{{ category.category_name }}</option>
									{% endfor %}
								</select>
							</div>
							<div class="form-group">
								<label>Item Name</label>
								<input type="text" name="item_name" class="form-control" placeholder="Enter item's name">
							</div>
							<div class="form-group">
								<label>Brand</label>
								<input type="text" name="brand" class="form-control" placeholder="Enter item's brand">
							</div>
							<div class="form-group">
								<label>Price</label>
								<input type="text" name="price" class="form-control" placeholder="Enter item's price">
							</div>
							<div class="form-group">
								<label>Quantity</label>
								<input type="text" name="quantity" class="form-control" placeholder="Enter item's stock">
							</div>
							<div class="form-group">
								<label>Description</label>
								<textarea class="form-control" name="description" rows="5"></textarea>
							</div>
							<div class="buttons">
								<button type="reset" class="btn btn-danger">Cancel</button>
								<button type="submit" class="btn btn-primary">Add Item</button>
							</div>
							
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/new-supplier.html
{% extends "base.html" %}

{% block title %}Add Supplier{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>Add Supplier</h3>
				</div>
				<div class="panel-body">
					<div class="col-md-offset-3 col-md-6">
						<form class="form form-horizontal" method="POST" action="{% url 'inventory:register_supplier' %}">{% csrf_token%}
							<div class="form-group">
								<label>Supplier's name</label>
								<input type="text" name="supplier_name" class="form-control" placeholder="Enter supplier's name" required>
							</div>
							<div class="form-group">
								<label>Contact</label>
								<input type="text" name="contact" class="form-control" placeholder="Enter supplier's contact">
							</div>
							<div class="buttons">
								<button type="reset" class="btn btn-danger">Cancel</button>
								<button type="submit" class="btn btn-primary">Add supplier</button>
							</div>
							
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/record-sale.html
{% extends "base.html" %}

{% block title %}Record Sale{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3>Record_sale</h3>
				</div>
				<div class="panel-body">
					<div class="col-md-offset-3 col-md-6">
						<form class="form form-horizontal" method="POST" action="{% url 'inventory:record_sale' %}">{% csrf_token%}
							<input type="hidden" name="item" value="{{ item.pk }}">
							<div class="form-group">
								<label>Item name</label>
								<input type="text" name="item_name" class="form-control" value="{{ item.item_name }}" required disabled>
							</div>
							<div class="form-group">
								<label>Quantity</label>
								<input type="text" name="quantity" class="form-control" placeholder="Enter item quantity">
							</div>
							<div class="buttons">
								<button type="reset" class="btn btn-danger">Cancel</button>
								<button type="submit" class="btn btn-primary">Record sale</button>
							</div>
							
						</form>
					</div>
					
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/sales-records.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Sales Records{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages %}
			<div {% ifequal message.tags 'error' %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endifequal %}>{{ message }}</div>
			{% endfor %}
			{% endif %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a data-toggle="modal" href="#saleModal" class="btn btn-primary pull-right">Record Sale</a>
					<h3>All Sales</h3>
				</div>
				<div class="panel-body">
					<table class="table table-bordered table-responsive">
						<thead>
							<th>Sale #</th>
							<th>Item</th>
							<th>Quantity</th>
							<th>Amount</th>
							<th>Sold on</th>
						</thead>
						<tbody>
							{% for sale in sales %}
							<tr>
								<td><a href="">{{ sale.pk }}</a></td>
								<td>{{ sale.item }}</td>
								<td>{{ sale.quantity | intcomma }}</td>
								<td>Ksh.{{ sale.amount | intcomma }}</td>
								<td>{{ sale.date_sold }}</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="4"><h3>No sales recorded yet</h3></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/suppliers.html
{% extends "base.html" %}

{% block title %}Suppliers{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages %}
			<div {% ifequal message.tags 'error' %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endifequal %}>{{ message }}</div>
			{% endfor %}
			{% endif %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{% url 'inventory:new_supplier' %}" class="btn btn-primary pull-right">Add supplier</a>
					<h3>All Suppliers</h3>
				</div>
				<div class="panel-body">
					<table class="table">
						<thead>
							<th>Supplier</th>
							<th>Contact</th>
							<th>Added on</th>
						</thead>
						<tbody>
							{% for supplier in suppliers %}
							<tr>
								<td><a href="">{{ supplier.supplier_name }}</a></td>
								<td>{{ supplier.contact }}</td>
								<td>{{ supplier.added_on }}</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="4"><h3>No suppliers registered yet</h3></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

inventory/templates/inventory/supply-records.html
{% extends "base.html" %}
{% load humanize %}

{% block title %}Supply Records{% endblock %}

{% block content %}
	<div class="row">
		<div class="col-md-12">
			{% if messages %}
			{% for message in messages %}
			<div {% ifequal message.tags 'error' %} class="alert alert-danger" {% else %} class="alert alert-{{ message.tags }}" {% endifequal %}>{{ message }}</div>
			{% endfor %}
			{% endif %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{% url 'inventory:add_supply_record' %}" class="btn btn-primary pull-right">Record Supply</a>
					<h3>All Records</h3>
				</div>
				<div class="panel-body">
					<table class="table table-bordered table-responsive">
						<thead>
							<th>Supply #</th>
							<th>Supplier</th>
							<th>Item</th>
							<th>Quantity</th>
							<th>Amount</th>
							<th>Supplied on</th>
							<th>Pay Status</th>
						</thead>
						<tbody>
							{% for record in records %}
							<tr>
								<td><a href="">{{ record.pk }}</a></td>
								<td>{{ record.supplier }}</td>
								<td>{{ record.items_supplied }}</td>
								<td>{{ record.quantity | intcomma }}</td>
								<td>Ksh.{{ record.amount | intcomma }}</td>
								<td>{{ record.date_supplied }}</td>
								<td>
									{% ifequal record.pay_status 0 %} 
									<font color="red">Pending</font>
									{% else %}
									<font color="green">Paid</font>
									{% endifequal %}
								</td>
							</tr>
							{% empty %}
							<tr>
								<td colspan="4"><h3>No supply details recorded yet</h3></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</div>

{% endblock %}