authentication/urls.py
from django.conf.urls import url

from . import views

app_name = 'authentication' 

urlpatterns = [
	url(r'^accounts/$', views.all_accounts, name='accounts'),
	url(r'^add-account/$', views.new_account, name='add_account'),
	url(r'^register-user/$', views.register_user, name='register_user'),
	url(r'^delete-account/(?P<account>\d+)/$', views.delete_account, name='delete-account'),
]

hardware_store/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/$', auth_views.login, {'template_name': 'authentication/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'', include('inventory.urls', namespace='inventory')),
]

inventory/urls.py
from django.conf.urls import url

from . import views

app_name = 'inventory'

urlpatterns = [
	url(r'^$', views.dashboard, name='dashboard'),
	# Categories
	url(r'^item-categories/$', views.item_categories, name='item_categories'),
	url(r'^register-category/$', views.register_category, name='register_category'),
	url(r'^category/(?P<pk>\d+)/detail/$', views.category_detail, name='category_detail'),
	# Suppliers
	url(r'^new-supplier/$', views.new_supplier, name='new_supplier'),
	url(r'^register-supplier/$', views.register_supplier, name='register_supplier'),
	url(r'^suppliers/$', views.suppliers, name='suppliers'),
	# Items
	url(r'^new-item/$', views.new_item, name='new_item'),
	url(r'^register-item/$', views.register_item, name='register_item'),
	url(r'^add-stock/(?P<item>\d+)/$', views.add_stock, name='add_stock'),
	url(r'^update-stock/$', views.update_stock, name='update_stock'),
	# Sale
	url(r'^sales/$', views.sales, name='sales'),
	url(r'^get-item/(?P<item>\d+)/$', views.get_item, name='get_item'),
	url(r'^record-sale/$', views.record_sale, name='record_sale'),
	# Supply records
	url(r'^supply-records/$', views.supply_records, name='supply_records'),
	url(r'^add-supply/$', views.new_supply_record, name='add_supply_record'),
	url(r'^register-supply/$', views.record_supply, name='record_supply'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>IMS - {% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<!--// Stylesheets //-->
<link href="{% static 'assets/css/style.css' %}" rel="stylesheet" media="screen" />
<link href="{% static 'assets/css/bootstrap.css' %}" rel="stylesheet" media="screen" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
<link href="{% static 'assets/css/custom.css' %}" rel="stylesheet" media="screen" />
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js' %}"></script>
<![endif]-->
</head>

<body>
<!-- Wrapper Start -->
<div class="wrapper">
    <div class="structure-row">
        <!-- Sidebar Start -->
        {% include "sidebar.html" %}
        <!-- Sidebar End -->
        <!-- Right Section Start -->
        <div class="right-sec">
            <!-- Right Section Header Start -->
            {% include "topbar.html" %}
            <!-- Right Section Header End -->
            <!-- Content Section Start -->
            <div class="content-section">
                <div class="container-liquid">
                    
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <!-- Content Section End -->
        </div>
        <!-- Right Section End -->
    </div>
</div>
<!-- Wrapper End -->

<!-- Add Category Modal -->
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Add Item Category</h4>
            </div>
            <div class="modal-body">
                <form class="form" method="POST" action="{% url 'inventory:register_category' %}">{% csrf_token %}
                  <div class="form-group">
            <label>Category</label>
            <input type="text" name="category_name" class="form-control" placeholder="Enter category name" required>
          </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save category</button>
            </div>
            </form>
    
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Record Sales Modal -->
<div id="saleModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">{{ item.item_name }} Sale Record</h4>
            </div>
            <div class="modal-body">
                <form class="form" method="POST" action="{% url 'inventory:record_sale' %}">{% csrf_token %}
                  <div class="form-group">
                    <label>Item</label>
                    <select name="item" class="form-control selectpicker" id="item-search" data-live-search="true" required>
                      <option value="" disabled selected>--Pick item--</option>
                      {% for item in items %}
                      <option value="{{ item.pk }}">{{ item.item_name }}</option>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="form-group">
                    <label>Quantity</label>
                    <input type="text" name="quantity" class="form-control" placeholder="Enter quantity sold" required>
                  </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save sale</button>
            </div>
            </form>
    
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!--// Javascript //-->
<script type="text/javascript" src="{% static 'assets/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.accordion.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.custom-scrollbar.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/icheck.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/selectnav.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/functions.js' %}"></script>

<!-- Graphs -->
<script type="text/javascript" src="{% static 'assets/js/raphael-2.1.0.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/morris-0.4.1.min.js' %}"></script>

<script type="text/javascript" src="{% static 'assets/js/jqvmap/jquery.vmap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jqvmap/jquery.vmap.sampledata.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jqvmap/maps/jquery.vmap.usa.js' %}"></script>

<!-- Live search dropdown -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>


<script>
    jQuery(document).ready(function() {
        jQuery('#usamap').vectorMap({
            map: 'usa_en',
            backgroundColor: '#33363f',
            color: '#ffffff',
            hoverOpacity: 0.7,
            selectedColor: '#999999',
            enableZoom: true,
            showTooltip: true,
            values: sample_data,
            scaleColors: ['#54acc0', '#e9535e'],
            normalizeFunction: 'polynomial'
        });
    });
</script>

<script>
    /* data stolen from http://howmanyleft.co.uk/vehicle/jaguar_'e'_type */
    var sale_data = [
      {% for sale in sales_graph %}
      {% for item in items %}
      {% ifequal item.pk sale.item %}
      {"item": "{{ item.item_name }}", "amount": {{ sale.total_amount}}},
      {% endifequal %}
      {% endfor %}
      {% endfor %}
    ];
    Morris.Bar({
      element: 'salesBarGraph',
      data: sale_data,
      xkey: 'item',
      ykeys: ['amount'],
      labels: ['Amount'],
      xLabelAngle: 45,
      barColors: ['#4ac18e']
      
    });
</script>

<script>
    /* data stolen from http://howmanyleft.co.uk/vehicle/jaguar_'e'_type */
    var sale_data = [
      {% for sale in sales_graph %}
      {% for item in items %}
      {% ifequal item.pk sale.item %}
      {"item": "{{ item.item_name }}", "amount": {{ sale.total_amount}}},
      {% endifequal %}
      {% endfor %}
      {% endfor %}
    ];
    Morris.Donut({
      element: 'profitLossGraph',
      data: [
        {label: "Sales", value: {{ sales.total_sales }} },
        {label: "Expenses", value: {{ expenses.total_expenses }} }
      ],
      labels: ['item'],
      resize: true,
      colors: ['#4ac18e', '#FF0000']
      
    });
</script>

<script type="text/javascript">
$(".selectpicker").chosen();
</script>



<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42761673-1', 'extracoding.com');
  ga('send', 'pageview');

</script>

</body>
</html>

<!-- Localized -->

templates/sidebar.html
{% load static %}
<aside class="sidebar">
    <div class="sidebar-in">
        <!-- Sidebar Header Start -->
        <header>
            <!-- Logo Start -->
            <div class="logo">
                <a href="dashboard1.html"><img src="{% static 'assets/images/logo.png' %}" alt="Adminise" /></a>
            </div>
            <!-- Logo End -->
            <!-- Toggle Button Start -->
            <a href="#" class="togglemenu">&nbsp;</a>
            <!-- Toggle Button End -->
            <div class="clearfix"></div>
        </header>
        <!-- Sidebar Header End -->
        <!-- Sidebar Navigation Start -->
        <nav class="navigation">
            <ul class="navi-acc" id="nav2">
                <li>
                <a href="{% url 'inventory:dashboard' %}" class="dashboard">Dashboard</a>
                </li>

                <li>
                    <a href="{% url 'inventory:item_categories' %}" class="layouts">Items</a>
                </li>

                <li>
                <a href="{% url 'inventory:sales' %}" class="ui-elements">Sales</a>
                
                </li>
                
                <li>
                    <a href="{% url 'inventory:suppliers' %}" class="pages">Suppliers<!-- <span class="label label-custom1">05</span> --></a>
                </li>

                <li>
                <a href="#" class="charts">Supply Records</a>
                <ul>
                    <li><a href="{% url 'inventory:add_supply_record' %}">Add record</a></li>
                    <li><a href="{% url 'inventory:supply_records' %}">Supply list</a></li>
                </ul>

                <li>
                    <a href="{% url 'authentication:accounts' %}" class="loginoptions">Accounts</a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </nav>
        <!-- Sidebar Navigation End -->
        <!-- Shadow Start -->
        <span class="shadows"></span>
        <!-- Shadow End -->
    </div>
</aside>

templates/topbar.html
{% load static %}
<header>
    <!-- User Section Start -->
    <div class="user">
        <figure>
            <a href="#"><img src="{% static 'assets/images/avatar1.jpg' %}" alt="Adminise" /></a>
        </figure>
        <div class="welcome">
            <p>Welcome</p>
            <h5><a href="#">{{ user.username }}</a></h5>
        </div>
    </div>
    <!-- User Section End -->
    <!-- Search Section Start -->
    <div class="search-box">
        <input type="text" placeholder="Search Anything" />
        <input type="submit" value="go" />
    </div>
    <!-- Search Section End -->
    <!-- Header Top Navigation Start -->
    <nav class="topnav">
        <ul id="nav1">
            <li class="tasks">
                <a href="#"><i class="glyphicon glyphicon-check"></i>Tasks<span>(04)</span></a>
                <div class="popdown">
                    <div class="taskslist">
                        <ul>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a><span class="pull-right">25%</span></h6>
                                <div class="progress">
                                    <div style="width: 15%" class="progress-bar progress-bar-success">
                                        <span class="sr-only">35% Complete (success)</span>
                                    </div>
                                    <div style="width: 5%" class="progress-bar progress-bar-warning">
                                        <span class="sr-only">20% Complete (warning)</span>
                                    </div>
                                    <div style="width: 5%" class="progress-bar progress-bar-danger">
                                        <span class="sr-only">10% Complete (danger)</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a><span class="pull-right">75%</span></h6>
                                <div class="progress">
                                    <div style="width: 30%" class="progress-bar progress-bar-success">
                                        <span class="sr-only">35% Complete (success)</span>
                                    </div>
                                    <div style="width: 30%" class="progress-bar progress-bar-warning">
                                        <span class="sr-only">20% Complete (warning)</span>
                                    </div>
                                    <div style="width: 15%" class="progress-bar progress-bar-danger">
                                        <span class="sr-only">10% Complete (danger)</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a><span class="pull-right">52%</span></h6>
                                <div class="progress">
                                    <div style="width: 30%" class="progress-bar progress-bar-success">
                                        <span class="sr-only">35% Complete (success)</span>
                                    </div>
                                    <div style="width: 15%" class="progress-bar progress-bar-warning">
                                        <span class="sr-only">20% Complete (warning)</span>
                                    </div>
                                    <div style="width: 7%" class="progress-bar progress-bar-danger">
                                        <span class="sr-only">10% Complete (danger)</span>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a><span class="pull-right">90%</span></h6>
                                <div class="progress">
                                    <div style="width: 30%" class="progress-bar progress-bar-success">
                                        <span class="sr-only">35% Complete (success)</span>
                                    </div>
                                    <div style="width: 30%" class="progress-bar progress-bar-warning">
                                        <span class="sr-only">20% Complete (warning)</span>
                                    </div>
                                    <div style="width: 30%" class="progress-bar progress-bar-danger">
                                        <span class="sr-only">10% Complete (danger)</span>
                                    </div>
                                </div>
                            </li>
                        </ul>
                        <a href="#" class="viewall">View All Tasks</a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </li>
            <li class="notifi">
                <a href="#"><i class="glyphicon glyphicon-bell"></i>Notifications</a>
                <div class="popdown">
                    <div class="notificationlist">
                        <ul>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a></h6>
                                <p>In parturient! Vel lundium natoque</p>
                                <span><i class="glyphicon glyphicon-time"></i>2hrs ago</span>
                            </li>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a></h6>
                                <p>In parturient! Vel lundium natoque</p>
                                <span><i class="glyphicon glyphicon-time"></i>2hrs ago</span>
                            </li>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a></h6>
                                <p>In parturient! Vel lundium natoque</p>
                                <span><i class="glyphicon glyphicon-time"></i>2hrs ago</span>
                            </li>
                            <li>
                                <h6><a href="#">Vel lundium natoque</a></h6>
                                <p>In parturient! Vel lundium natoque</p>
                                <span><i class="glyphicon glyphicon-time"></i>2hrs ago</span>
                            </li>
                        </ul>
                        <a href="#" class="viewall">View All Notifications</a>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </li>
            <li class="settings">
                <a href="#"><i class="glyphicon glyphicon-wrench"></i>Settings</a>
                <div class="popdown popdown-right settings">
                    <nav>
                        <a href="#"><i class="glyphicon glyphicon-user"></i>Your Profile</a>
                        <a href="#"><i class="glyphicon glyphicon-pencil"></i>Edit Account</a>
                        <a href="#"><i class="glyphicon glyphicon-question-sign"></i>Get Help</a>
                        <a href="{% url 'logout' %}"><i class="glyphicon glyphicon-log-out"></i>Log out</a>
                    </nav>
                </div>
            </li>
        </ul>
    </nav>
    <!-- Header Top Navigation End -->
    <div class="clearfix"></div>
</header>